lastupdatecheck: 0
recentrepos:
- /Users/mjbouvet/workplace/VendorLeadTimeCoralService/src/VendorLeadTimeCoralService
- /Users/mjbouvet/workplace/VendorLeadTimeCoralService/src/VendorLeadTimeConfigCommon
- /Users/mjbouvet/workplace/VendorLeadTimeCoralService/src/VendorLeadTimeACSConfigJavaClient
- /Users/mjbouvet/ghq/github.com/bouvettem17/spotify-stories
- /Users/mjbouvet/ghq/github.com/bouvettem17/portfolio-website
startuppopupversion: 5
customcommandshistory:
- qa!
- qa
- q
hidecommandlog: false
ignorewhitespaceindiffview: false
